//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_AUDIOCONTROLIF_H_
#define MOCK_AUDIOCONTROLIF_H_

#include "Sdk/Fb/AudioControlIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class AudioControlMock: public SdkNs::AudioControlIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::AudioControlClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(favorite, void(int ubieValue));

	MOCK_METHOD1(favoriteConfig, void(const SdkNs::AudioControlDef::favoriteConf& conf));

	MOCK_METHOD1(playPause, void(bool ubieValue));

	MOCK_METHOD1(playPauseConfig, void(const SdkNs::AudioControlDef::playPauseConf& conf));

	MOCK_METHOD1(volume, void(int ubieValue));

	MOCK_METHOD1(volumeConfig, void(const SdkNs::AudioControlDef::volumeConf& conf));

	MOCK_METHOD1(favoriteCompleted, void(bool success));

	MOCK_METHOD1(nextCompleted, void(bool success));

	MOCK_METHOD1(prevCompleted, void(bool success));

	MOCK_METHOD1(volumeDownCompleted, void(bool success));

	MOCK_METHOD1(volumeUpCompleted, void(bool success));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::AudioControlDef::HistoryState>&));
};
}
#endif /* MOCK_AUDIOCONTROLIF_H_ */
