//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_GAUGEIF_H_
#define MOCK_GAUGEIF_H_

#include "Sdk/Fb/GaugeIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class GaugeMock: public SdkNs::GaugeIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::GaugeClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(averageValue, void(double ubieValue));

	MOCK_METHOD1(averageValueConfig, void(const SdkNs::GaugeDef::averageValueConf& conf));

	MOCK_METHOD1(consumptionValue, void(double ubieValue));

	MOCK_METHOD1(consumptionValueConfig, void(const SdkNs::GaugeDef::consumptionValueConf& conf));

	MOCK_METHOD1(currentPercentage, void(int ubieValue));

	MOCK_METHOD1(currentPercentageConfig, void(const SdkNs::GaugeDef::currentPercentageConf& conf));

	MOCK_METHOD1(currentValue, void(double ubieValue));

	MOCK_METHOD1(currentValueConfig, void(const SdkNs::GaugeDef::currentValueConf& conf));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::GaugeDef::HistoryState>&));
};
}
#endif /* MOCK_GAUGEIF_H_ */
