//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_HEALTHBOXROOMIF_H_
#define MOCK_HEALTHBOXROOMIF_H_

#include "Sdk/Fb/HealthBoxRoomIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class HealthBoxRoomMock: public SdkNs::HealthBoxRoomIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::HealthBoxRoomClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(boostRemaining, void(int ubieValue));

	MOCK_METHOD1(boostRemainingConfig, void(const SdkNs::HealthBoxRoomDef::boostRemainingConf& conf));

	MOCK_METHOD1(boostTimeout, void(int ubieValue));

	MOCK_METHOD1(boostTimeoutConfig, void(const SdkNs::HealthBoxRoomDef::boostTimeoutConf& conf));

	MOCK_METHOD1(boostValue, void(int ubieValue));

	MOCK_METHOD1(boostValueConfig, void(const SdkNs::HealthBoxRoomDef::boostValueConf& conf));

	MOCK_METHOD1(currentFlowRate, void(double ubieValue));

	MOCK_METHOD1(currentFlowRateConfig, void(const SdkNs::HealthBoxRoomDef::currentFlowRateConf& conf));

	MOCK_METHOD1(boostCompleted, void(bool success));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::HealthBoxRoomDef::HistoryState>&));
};
}
#endif /* MOCK_HEALTHBOXROOMIF_H_ */
