//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_SHUTTERUPDOWNIF_H_
#define MOCK_SHUTTERUPDOWNIF_H_

#include "Sdk/Fb/ShutterUpDownIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class ShutterUpDownMock: public SdkNs::ShutterUpDownIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::ShutterUpDownClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(registerStateValues, void(const std::vector<std::string>& enumValues));

	MOCK_METHOD1(state, void(std::string ubieValue));

	MOCK_METHOD1(stateConfig, void(const SdkNs::ShutterUpDownDef::stateConf& conf));

	MOCK_METHOD1(shutterDownCompleted, void(bool success));

	MOCK_METHOD1(shutterStopCompleted, void(bool success));

	MOCK_METHOD1(shutterUpCompleted, void(bool success));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::ShutterUpDownDef::HistoryState>&));
};
}
#endif /* MOCK_SHUTTERUPDOWNIF_H_ */
