//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_SHUTTERPOSITIONIF_H_
#define MOCK_SHUTTERPOSITIONIF_H_

#include "Sdk/Fb/ShutterPositionIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class ShutterPositionMock: public SdkNs::ShutterPositionIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::ShutterPositionClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(shutterPosition, void(int ubieValue));

	MOCK_METHOD1(shutterPositionConfig, void(const SdkNs::ShutterPositionDef::shutterPositionConf& conf));

	MOCK_METHOD1(shutterDownCompleted, void(bool success));

	MOCK_METHOD1(shutterUpCompleted, void(bool success));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::ShutterPositionDef::HistoryState>&));
};
}
#endif /* MOCK_SHUTTERPOSITIONIF_H_ */
