//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_SPEAKERSYSTEMIF_H_
#define MOCK_SPEAKERSYSTEMIF_H_

#include "Sdk/Fb/SpeakerSystemIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class SpeakerSystemMock: public SdkNs::SpeakerSystemIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::SpeakerSystemClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(favorites, void(std::string ubieValue));

	MOCK_METHOD1(favoritesConfig, void(const SdkNs::SpeakerSystemDef::favoritesConf& conf));

	MOCK_METHOD1(members, void(std::string ubieValue));

	MOCK_METHOD1(membersConfig, void(const SdkNs::SpeakerSystemDef::membersConf& conf));

	MOCK_METHOD1(createGroupCompleted, void(bool success));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::SpeakerSystemDef::HistoryState>&));
};
}
#endif /* MOCK_SPEAKERSYSTEMIF_H_ */
