//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_VENTILATIONIF_H_
#define MOCK_VENTILATIONIF_H_

#include "Sdk/Fb/VentilationIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class VentilationMock: public SdkNs::VentilationIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::VentilationClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(co2, void(int ubieValue));

	MOCK_METHOD1(co2Config, void(const SdkNs::VentilationDef::co2Conf& conf));

	MOCK_METHOD1(registerCurrRegimeValues, void(const std::vector<std::string>& enumValues));

	MOCK_METHOD1(currRegime, void(std::string ubieValue));

	MOCK_METHOD1(currRegimeConfig, void(const SdkNs::VentilationDef::currRegimeConf& conf));

	MOCK_METHOD1(humidity, void(int ubieValue));

	MOCK_METHOD1(humidityConfig, void(const SdkNs::VentilationDef::humidityConf& conf));

	MOCK_METHOD1(refresh, void(int ubieValue));

	MOCK_METHOD1(refreshConfig, void(const SdkNs::VentilationDef::refreshConf& conf));

	MOCK_METHOD1(voc, void(int ubieValue));

	MOCK_METHOD1(vocConfig, void(const SdkNs::VentilationDef::vocConf& conf));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::VentilationDef::HistoryState>&));
};
}
#endif /* MOCK_VENTILATIONIF_H_ */
