//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef MOCK_WARMWCOLDWIF_H_
#define MOCK_WARMWCOLDWIF_H_

#include "Sdk/Fb/WarmWColdWIf.h"
#include "gtest/gtest.h"
#include "gmock/gmock.h"

#include <vector>
#include <map>


namespace SdkNs
{
class WarmWColdWMock: public SdkNs::WarmWColdWIf
{
public:
	MOCK_CONST_METHOD0(id, std::string());
	MOCK_CONST_METHOD0(name, std::string());
	MOCK_METHOD1(name, void(const std::string& name));
	MOCK_METHOD1(variant, void(const std::string& variant));
	MOCK_CONST_METHOD0(location, std::string());
	MOCK_METHOD1(location, void(const std::string& location));
	MOCK_METHOD1(locationId, void(int locationId));
	MOCK_METHOD1(refId, void(const std::string& refId));
	MOCK_METHOD0(commit, void());
	MOCK_METHOD3(cloudMessage, void(SdkNs::SdkMessageLevel, const std::string& , const std::map<int, std::string>& ));
	MOCK_METHOD1(registerClient, void(SdkNs::WarmWColdWClientIf*));
	MOCK_METHOD0(unRegisterClient, void());

	MOCK_METHOD1(brightness, void(double ubieValue));

	MOCK_METHOD1(brightnessConfig, void(const SdkNs::WarmWColdWDef::brightnessConf& conf));

	MOCK_METHOD1(currRegime, void(std::string ubieValue));

	MOCK_METHOD1(currRegimeConfig, void(const SdkNs::WarmWColdWDef::currRegimeConf& conf));

	MOCK_METHOD1(on, void(bool ubieValue));

	MOCK_METHOD1(onConfig, void(const SdkNs::WarmWColdWDef::onConf& conf));

	MOCK_METHOD1(presetColor, void(int ubieValue));

	MOCK_METHOD1(presetColorConfig, void(const SdkNs::WarmWColdWDef::presetColorConf& conf));

	MOCK_METHOD1(registerPresetColorValues, void(const std::vector<WarmWColdWDef::PresetColorValue>& presetValues));

	MOCK_METHOD1(presetMovie, void(int ubieValue));

	MOCK_METHOD1(presetMovieConfig, void(const SdkNs::WarmWColdWDef::presetMovieConf& conf));

	MOCK_METHOD1(registerPresetMovieValues, void(const std::vector<WarmWColdWDef::PresetMovieValue>& presetValues));

	MOCK_METHOD1(temperature, void(double ubieValue));

	MOCK_METHOD1(temperatureConfig, void(const SdkNs::WarmWColdWDef::temperatureConf& conf));

	MOCK_METHOD1(commitHistory, void(const std::vector<SdkNs::WarmWColdWDef::HistoryState>&));
};
}
#endif /* MOCK_WARMWCOLDWIF_H_ */
