//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/* 
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCK_DEFINITIONS_ANALOGIF_H_
#define FUNCTIONBLOCK_DEFINITIONS_ANALOGIF_H_
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

namespace SdkNs {
namespace AnalogDef
{

    struct valueConf
    {
        valueConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "value" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "value" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "value" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "value"
         */
        boost::optional<double> min;
        /**
         * The maximum value of property "value"
         */
        boost::optional<double> max;
        /**
         * The step value of property "value"
         */
        boost::optional<double> step;
        /**
         * The unit value of property "value"
         */
        boost::optional<std::string> unit;

    };

    struct HistoryState
    {
        HistoryState():  timeUTC(), value() {};

        /**
         * The epoch time of this event
         */
        time_t timeUTC;
	    boost::optional<double> value;

    };
}
}
#endif
