//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_GAUGEIF_H_
#define FUNCTIONBLOCKS_GAUGEIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "GaugeDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::GaugeIf
 * \brief
 * Represents a Gauge (Meter).
 * Properties:
 *  - averageValue
 *  - consumptionValue
 *  - currentPercentage
 *  - currentValue

 */

namespace SdkNs {
class GaugeClientIf;

class GaugeIf: public FunctionBlockIf
{
public:
	virtual ~GaugeIf() {};

	/**
	 * Register a client that will listen to events from this Gauge FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(GaugeClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the Gauge FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void averageValue(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void averageValueConfig(const SdkNs::GaugeDef::averageValueConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void consumptionValue(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void consumptionValueConfig(const SdkNs::GaugeDef::consumptionValueConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currentPercentage(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currentPercentageConfig(const SdkNs::GaugeDef::currentPercentageConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currentValue(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currentValueConfig(const SdkNs::GaugeDef::currentValueConf& conf) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::GaugeDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_GAUGEIF_H_ */
