//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/* 
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCK_DEFINITIONS_GAUGEIF_H_
#define FUNCTIONBLOCK_DEFINITIONS_GAUGEIF_H_
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

namespace SdkNs {
namespace GaugeDef
{

    struct averageValueConf
    {
        averageValueConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "averageValue" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "averageValue" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "averageValue" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "averageValue"
         */
        boost::optional<double> min;
        /**
         * The maximum value of property "averageValue"
         */
        boost::optional<double> max;
        /**
         * The step value of property "averageValue"
         */
        boost::optional<double> step;
        /**
         * The unit value of property "averageValue"
         */
        boost::optional<std::string> unit;

    };

    struct consumptionValueConf
    {
        consumptionValueConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "consumptionValue" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "consumptionValue" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "consumptionValue" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "consumptionValue"
         */
        boost::optional<double> min;
        /**
         * The maximum value of property "consumptionValue"
         */
        boost::optional<double> max;
        /**
         * The step value of property "consumptionValue"
         */
        boost::optional<double> step;
        /**
         * The unit value of property "consumptionValue"
         */
        boost::optional<std::string> unit;

    };

    struct currentPercentageConf
    {
        currentPercentageConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "currentPercentage" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "currentPercentage" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "currentPercentage" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "currentPercentage"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "currentPercentage"
         */
        boost::optional<int> max;
        /**
         * The step value of property "currentPercentage"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "currentPercentage"
         */
        boost::optional<std::string> unit;

    };

    struct currentValueConf
    {
        currentValueConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "currentValue" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "currentValue" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "currentValue" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "currentValue"
         */
        boost::optional<double> min;
        /**
         * The maximum value of property "currentValue"
         */
        boost::optional<double> max;
        /**
         * The step value of property "currentValue"
         */
        boost::optional<double> step;
        /**
         * The unit value of property "currentValue"
         */
        boost::optional<std::string> unit;

    };

    struct HistoryState
    {
        HistoryState():  timeUTC(), averageValue(), consumptionValue(), currentPercentage(), currentValue() {};

        /**
         * The epoch time of this event
         */
        time_t timeUTC;
	    boost::optional<double> averageValue;
	    boost::optional<double> consumptionValue;
	    boost::optional<int> currentPercentage;
	    boost::optional<double> currentValue;

    };
}
}
#endif
