//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_HEALTHBOXROOMIF_H_
#define FUNCTIONBLOCKS_HEALTHBOXROOMIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "HealthBoxRoomDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::HealthBoxRoomIf
 * \brief
 * 
 * Properties:
 *  - boostRemaining
 *  - boostTimeout
 *  - boostValue
 *  - currentFlowRate
 * Actions:
 *  - boost

 */

namespace SdkNs {
class HealthBoxRoomClientIf;

class HealthBoxRoomIf: public FunctionBlockIf
{
public:
	virtual ~HealthBoxRoomIf() {};

	/**
	 * Register a client that will listen to events from this HealthBoxRoom FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(HealthBoxRoomClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the HealthBoxRoom FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void boostRemaining(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void boostRemainingConfig(const SdkNs::HealthBoxRoomDef::boostRemainingConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void boostTimeout(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void boostTimeoutConfig(const SdkNs::HealthBoxRoomDef::boostTimeoutConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void boostValue(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void boostValueConfig(const SdkNs::HealthBoxRoomDef::boostValueConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currentFlowRate(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currentFlowRateConfig(const SdkNs::HealthBoxRoomDef::currentFlowRateConf& conf) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the HealthBoxRoomClientIf::boost(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void boostCompleted(bool success) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::HealthBoxRoomDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_HEALTHBOXROOMIF_H_ */
