//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_HUMIDITYIF_H_
#define FUNCTIONBLOCKS_HUMIDITYIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "HumidityDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::HumidityIf
 * \brief
 * 
 * Properties:
 *  - currRegime
 *  - value

 */

namespace SdkNs {
class HumidityClientIf;

class HumidityIf: public FunctionBlockIf
{
public:
	virtual ~HumidityIf() {};

	/**
	 * Register a client that will listen to events from this Humidity FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(HumidityClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the Humidity FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Register the enum values for the CurrRegime property
	 * @param enumValues The enumvalues to register (each value must be unique)
	 */
	virtual void registerCurrRegimeValues(const std::vector<std::string>& enumValues) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currRegime(std::string ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currRegimeConfig(const SdkNs::HumidityDef::currRegimeConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void value(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void valueConfig(const SdkNs::HumidityDef::valueConf& conf) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::HumidityDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_HUMIDITYIF_H_ */
