//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/* 
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCK_DEFINITIONS_HUMIDITYIF_H_
#define FUNCTIONBLOCK_DEFINITIONS_HUMIDITYIF_H_
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

namespace SdkNs {
namespace HumidityDef
{

    struct currRegimeConf
    {
        currRegimeConf(): available(), readAllowed(), writeAllowed() {};
        /**
         * Is the property "currRegime" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "currRegime" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "currRegime" writable
         */
        boost::optional<bool> writeAllowed;

    };

    struct valueConf
    {
        valueConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "value" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "value" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "value" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "value"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "value"
         */
        boost::optional<int> max;
        /**
         * The step value of property "value"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "value"
         */
        boost::optional<std::string> unit;

    };

    struct HistoryState
    {
        HistoryState():  timeUTC(), currRegime(), value() {};

        /**
         * The epoch time of this event
         */
        time_t timeUTC;
	    boost::optional<std::string> currRegime;
	    boost::optional<int> value;

    };
}
}
#endif
