//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_NESTTHERMOIF_H_
#define FUNCTIONBLOCKS_NESTTHERMOIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "NestThermoDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::NestThermoIf
 * \brief
 * 
 * Properties:
 *  - currRegime
 *  - currTemp
 *  - isCooling
 *  - isHeating
 *  - setCoolTemp
 *  - setHeatTemp
 *  - setTemp

 */

namespace SdkNs {
class NestThermoClientIf;

class NestThermoIf: public FunctionBlockIf
{
public:
	virtual ~NestThermoIf() {};

	/**
	 * Register a client that will listen to events from this NestThermo FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(NestThermoClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the NestThermo FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Register the enum values for the CurrRegime property
	 * @param enumValues The enumvalues to register (each value must be unique)
	 */
	virtual void registerCurrRegimeValues(const std::vector<std::string>& enumValues) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currRegime(std::string ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currRegimeConfig(const SdkNs::NestThermoDef::currRegimeConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currTemp(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currTempConfig(const SdkNs::NestThermoDef::currTempConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void isCooling(bool ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void isCoolingConfig(const SdkNs::NestThermoDef::isCoolingConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void isHeating(bool ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void isHeatingConfig(const SdkNs::NestThermoDef::isHeatingConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void setCoolTemp(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void setCoolTempConfig(const SdkNs::NestThermoDef::setCoolTempConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void setHeatTemp(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void setHeatTempConfig(const SdkNs::NestThermoDef::setHeatTempConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void setTemp(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void setTempConfig(const SdkNs::NestThermoDef::setTempConf& conf) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::NestThermoDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_NESTTHERMOIF_H_ */
