//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_ONOFFIF_H_
#define FUNCTIONBLOCKS_ONOFFIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "OnOffDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::OnOffIf
 * \brief
 * Represents a component with a binary value. Typicaly a switch.
 * Properties:
 *  - value
 * Actions:
 *  - off
 *  - on

 */

namespace SdkNs {
class OnOffClientIf;

class OnOffIf: public FunctionBlockIf
{
public:
	virtual ~OnOffIf() {};

	/**
	 * Register a client that will listen to events from this OnOff FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(OnOffClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the OnOff FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void value(bool ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void valueConfig(const SdkNs::OnOffDef::valueConf& conf) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the OnOffClientIf::off(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void offCompleted(bool success) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the OnOffClientIf::on(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void onCompleted(bool success) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::OnOffDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_ONOFFIF_H_ */
