//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_SCENEIF_H_
#define FUNCTIONBLOCKS_SCENEIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "SceneDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::SceneIf
 * \brief
 * 
 * Actions:
 *  - active

 */

namespace SdkNs {
class SceneClientIf;

class SceneIf: public FunctionBlockIf
{
public:
	virtual ~SceneIf() {};

	/**
	 * Register a client that will listen to events from this Scene FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(SceneClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the Scene FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the SceneClientIf::active(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void activeCompleted(bool success) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::SceneDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_SCENEIF_H_ */
