//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_SHUTTERSLATSPOSITIONIF_H_
#define FUNCTIONBLOCKS_SHUTTERSLATSPOSITIONIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "ShutterSlatsPositionDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::ShutterSlatsPositionIf
 * \brief
 * 
 * Properties:
 *  - shutterPosition
 *  - slatPosition
 * Actions:
 *  - shutterDown
 *  - shutterUp
 *  - slatDown
 *  - slatUp

 */

namespace SdkNs {
class ShutterSlatsPositionClientIf;

class ShutterSlatsPositionIf: public FunctionBlockIf
{
public:
	virtual ~ShutterSlatsPositionIf() {};

	/**
	 * Register a client that will listen to events from this ShutterSlatsPosition FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(ShutterSlatsPositionClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the ShutterSlatsPosition FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void shutterPosition(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void shutterPositionConfig(const SdkNs::ShutterSlatsPositionDef::shutterPositionConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void slatPosition(double ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void slatPositionConfig(const SdkNs::ShutterSlatsPositionDef::slatPositionConf& conf) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterSlatsPositionClientIf::shutterDown(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void shutterDownCompleted(bool success) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterSlatsPositionClientIf::shutterUp(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void shutterUpCompleted(bool success) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterSlatsPositionClientIf::slatDown(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void slatDownCompleted(bool success) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterSlatsPositionClientIf::slatUp(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void slatUpCompleted(bool success) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::ShutterSlatsPositionDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_SHUTTERSLATSPOSITIONIF_H_ */
