//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_SHUTTERUPDOWNIF_H_
#define FUNCTIONBLOCKS_SHUTTERUPDOWNIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "ShutterUpDownDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::ShutterUpDownIf
 * \brief
 * 
 * Properties:
 *  - state
 * Actions:
 *  - shutterDown
 *  - shutterStop
 *  - shutterUp

 */

namespace SdkNs {
class ShutterUpDownClientIf;

class ShutterUpDownIf: public FunctionBlockIf
{
public:
	virtual ~ShutterUpDownIf() {};

	/**
	 * Register a client that will listen to events from this ShutterUpDown FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(ShutterUpDownClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the ShutterUpDown FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Register the enum values for the State property
	 * @param enumValues The enumvalues to register (each value must be unique)
	 */
	virtual void registerStateValues(const std::vector<std::string>& enumValues) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void state(std::string ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void stateConfig(const SdkNs::ShutterUpDownDef::stateConf& conf) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterUpDownClientIf::shutterDown(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void shutterDownCompleted(bool success) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterUpDownClientIf::shutterStop(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void shutterStopCompleted(bool success) = 0;

	/**
	 * Notify the Sdk that the action was completed; this will cancel the timeout returned in the ShutterUpDownClientIf::shutterUp(const std::set<std::string>& properties) call
	 * @param success The action was successfull or not
	 */
	virtual void shutterUpCompleted(bool success) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::ShutterUpDownDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_SHUTTERUPDOWNIF_H_ */
