//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/* 
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCK_DEFINITIONS_SPEAKERIF_H_
#define FUNCTIONBLOCK_DEFINITIONS_SPEAKERIF_H_
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

namespace SdkNs {
namespace SpeakerDef
{

    struct volumeConf
    {
        volumeConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "volume" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "volume" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "volume" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "volume"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "volume"
         */
        boost::optional<int> max;
        /**
         * The step value of property "volume"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "volume"
         */
        boost::optional<std::string> unit;

    };

    struct HistoryState
    {
        HistoryState():  timeUTC(), volume() {};

        /**
         * The epoch time of this event
         */
        time_t timeUTC;
	    boost::optional<int> volume;

    };
}
}
#endif
