//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/* 
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCK_DEFINITIONS_SPEAKERSYSTEMIF_H_
#define FUNCTIONBLOCK_DEFINITIONS_SPEAKERSYSTEMIF_H_
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

namespace SdkNs {
namespace SpeakerSystemDef
{

    struct favoritesConf
    {
        favoritesConf(): available(), readAllowed(), writeAllowed() {};
        /**
         * Is the property "favorites" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "favorites" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "favorites" writable
         */
        boost::optional<bool> writeAllowed;

    };

    struct membersConf
    {
        membersConf(): available(), readAllowed(), writeAllowed() {};
        /**
         * Is the property "members" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "members" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "members" writable
         */
        boost::optional<bool> writeAllowed;

    };

    struct HistoryState
    {
        HistoryState():  timeUTC(), favorites(), members() {};

        /**
         * The epoch time of this event
         */
        time_t timeUTC;
	    boost::optional<std::string> favorites;
	    boost::optional<std::string> members;

    };
}
}
#endif
