//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/* 
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCK_DEFINITIONS_VENTILATIONIF_H_
#define FUNCTIONBLOCK_DEFINITIONS_VENTILATIONIF_H_
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

namespace SdkNs {
namespace VentilationDef
{

    struct co2Conf
    {
        co2Conf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "co2" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "co2" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "co2" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "co2"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "co2"
         */
        boost::optional<int> max;
        /**
         * The step value of property "co2"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "co2"
         */
        boost::optional<std::string> unit;

    };

    struct currRegimeConf
    {
        currRegimeConf(): available(), readAllowed(), writeAllowed() {};
        /**
         * Is the property "currRegime" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "currRegime" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "currRegime" writable
         */
        boost::optional<bool> writeAllowed;

    };

    struct humidityConf
    {
        humidityConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "humidity" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "humidity" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "humidity" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "humidity"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "humidity"
         */
        boost::optional<int> max;
        /**
         * The step value of property "humidity"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "humidity"
         */
        boost::optional<std::string> unit;

    };

    struct refreshConf
    {
        refreshConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "refresh" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "refresh" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "refresh" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "refresh"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "refresh"
         */
        boost::optional<int> max;
        /**
         * The step value of property "refresh"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "refresh"
         */
        boost::optional<std::string> unit;

    };

    struct vocConf
    {
        vocConf(): available(), readAllowed(), writeAllowed(), min(), max(), step(), unit() {};
        /**
         * Is the property "voc" available (does this functionblock implement this property)
         */
        boost::optional<bool> available;
        /**
         * is the value of property "voc" readable
         */
        boost::optional<bool> readAllowed;
        /**
         * is the value of property "voc" writable
         */
        boost::optional<bool> writeAllowed;

        /**
         * The minimum value of property "voc"
         */
        boost::optional<int> min;
        /**
         * The maximum value of property "voc"
         */
        boost::optional<int> max;
        /**
         * The step value of property "voc"
         */
        boost::optional<int> step;
        /**
         * The unit value of property "voc"
         */
        boost::optional<std::string> unit;

    };

    struct HistoryState
    {
        HistoryState():  timeUTC(), co2(), currRegime(), humidity(), refresh(), voc() {};

        /**
         * The epoch time of this event
         */
        time_t timeUTC;
	    boost::optional<int> co2;
	    boost::optional<std::string> currRegime;
	    boost::optional<int> humidity;
	    boost::optional<int> refresh;
	    boost::optional<int> voc;

    };
}
}
#endif
