//File generated by Functionblock Generator
// !!!! DO NOT EDIT MANUALLY !!!!
/*
 * Copyright 2018 Qbus n.v.
 */

#ifndef FUNCTIONBLOCKS_VENTILATIONIF_H_
#define FUNCTIONBLOCKS_VENTILATIONIF_H_
#include "Sdk/FunctionBlockIf.h"
#include "VentilationDefinitions.h"
#include <string>
#include <set>
#include <vector>
#include <stdint.h>
#include <boost/optional.hpp>

/**
 * \class SdkNs::VentilationIf
 * \brief
 * 
 * Properties:
 *  - co2
 *  - currRegime
 *  - humidity
 *  - refresh
 *  - voc

 */

namespace SdkNs {
class VentilationClientIf;

class VentilationIf: public FunctionBlockIf
{
public:
	virtual ~VentilationIf() {};

	/**
	 * Register a client that will listen to events from this Ventilation FunctionBlock
	 * @param client Pointer of the client
	 */
	virtual void registerClient(VentilationClientIf* client) = 0;

	/**
	 * Unregister the client that will listen to events of the Ventilation FunctionBlock
	 */
	virtual void unRegisterClient() = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void co2(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void co2Config(const SdkNs::VentilationDef::co2Conf& conf) = 0;

	/**
	 * Register the enum values for the CurrRegime property
	 * @param enumValues The enumvalues to register (each value must be unique)
	 */
	virtual void registerCurrRegimeValues(const std::vector<std::string>& enumValues) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void currRegime(std::string ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void currRegimeConfig(const SdkNs::VentilationDef::currRegimeConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void humidity(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void humidityConfig(const SdkNs::VentilationDef::humidityConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void refresh(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void refreshConfig(const SdkNs::VentilationDef::refreshConf& conf) = 0;

	/**
	 * Send value to the cloud. 
	 * @param ubieValue The Value to send to the cloud 
	 */
	virtual void voc(int ubieValue) = 0;

	/**
	 * Set the configuration of this property (read, write, step, unit)
	 * @param conf The configuration of the property
	 */
	virtual void vocConfig(const SdkNs::VentilationDef::vocConf& conf) = 0;

	/**
	 * Send a user message to the cloud, the message concerns this functionblock
	 * @param level Message severity level
	 * @param id The id of the message (messages.json)
	 * @param dataFields Zero or more fields that will we inserted in the message
	 */
	virtual void cloudMessage(SdkMessageLevel level, const std::string& id, const std::map<int, std::string>& dataFields) = 0;

	/**
	 * Commit history
	 * @param historyState A vector of history states
	 */
	virtual void commitHistory(const std::vector<SdkNs::VentilationDef::HistoryState>& historyState) = 0;
};
}

#endif /* FUNCTIONBLOCKS_VENTILATIONIF_H_ */
